language: go
go:
 - 1.8.1
 - release

script:
 - cp -Rf ../api-gateway ../../.. && cd ../../../api-gateway && go build -v && go test -v -i gateway_test.go
 - cp -Rf ../api-gateway ../../.. && cd ../../../api-gateway && go build --buildmode exe
